{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-metrics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Metrics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Metrics/Metrics_{{ version }}.tar.gz
  sha256: 7395694d57cc6efa33d2af8ef22f0e4b32ccfa22993f2a8e804f7d4ee5c2083a

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('Metrics')"           # [not win]
    - "\"%R%\" -e \"library('Metrics')\""  # [win]

about:
  home: https://github.com/mfrasco/Metrics
  license: BSD-3-Clause
  summary: An implementation of evaluation metrics in R that are commonly used in supervised machine learning. It implements metrics for regression, time series, binary classification, classification, and information retrieval problems. It has zero dependencies and a consistent, simple interface for all functions.
  license_family: BSD

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE
extra:
  recipe-maintainers:
    - conda-forge/r
