appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: SpufFg4BMsK1ibvD/ho93gHGoEI2WA23/Owc85+wHGtUuX1PQMk4nG5gyuTGBYlB+7N0z0liIgf4kkccWzqFR5+9PPDzH6/pdfGbklREF3vcxK+FuC37bG3NUmu1MvJl2hzGAGHoXEqDFY4+EZBhV6DNQ+O/TNb09KDpbVsCPoSkdue5lcd8dsLLY0iE7gLX/2F/5HaIWS2wu8og7754yKaeo7e0QWcuQPqL4WkbfI6dDW/tGAYbcLi2BhDkZ6qdbT18Xvj/Jjqo10Rye65bVCLGNg1NbkX40pEaVT3IK7rGcWazhqFxHw++Oi03O/GOdfdLesxEBtBf6eeVTFwHKYNdC3yRuUtAYGLEnw9e5Cxbwv7etJTTNt8tpwx6UzCnCCbvT1S+6CcvKB9RxCegHzj9cUvlMH4YZCGgq85kQDJsEEz33eX5mBYPxKEyTaw2HAkWUKK9MJnNF3gC906YvlPDRPrrng61JnRal2Umhbs9u43pQCqUzuZKev7xmCS+L0npJV7i5ozo8qKUBso/KhNloThYGUrkUjsi+dmXNMVVaO6YUDhqMeceiwF4Df4en5Fsz/RrmPC6CTCJ7di3hJ3d9ml6wsDzyyy7uPqk5TOXYA4L7Dlwnvo6bSqFyHmnEzZbI6JzcuHhlmzfD1hMx4vREXIaluHy74GfKQSmwG8=}
bot:
  automerge: true
